spring:
  datasource:
    username: "debian-sys-maint"
    password: "AzVXVo4L4BhRQ0PY"
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      test-on-borrow: true
      test-while-idle: true
    dbcp2:
      max-idle: 10
      min-idle: 5
      initial-size: 5
      validation-query: "SELECT 1"

    tomcat:
      max-active: 15
      remove-abandoned: true
      remove-abandoned-timeout: 180
      max-wait: 3000
      test-on-borrow: true

  thymeleaf:
    cache: false
    encoding: UTF-8
Server:
  port: 80




